Sample spring postgres graphql
keploy/samples-java pull request #61
Opened 2024-01-12 18:51 UTC by Rentox98

Signed-off-by: Alberto Cao <albertocao98@gmail.com>

# Pull Request Template

## Description

Creating sample java application using postgres and graphql, tested using Keploy.

Fixes [keploy/keploy#911](https://github.com/keploy/keploy/issues/911)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

The demo has been tested locally on a WSL2 environment with Docker, following the steps outlined in the project's README.

## Additional Context (Please include any Screenshots/gifs if relevant)

Capturing requests using Keploy record.

![doc_1](https://github.com/keploy/samples-java/assets/46230606/d890190d-b8f9-47a5-b7e3-2eddf54971fe)

From the GraphQL GUI run the queries

![doc_3](https://github.com/keploy/samples-java/assets/46230606/ec28c8b7-2372-488a-8cb6-fa192d7377a3)

Record requests with Keploy
![doc_2](https://github.com/keploy/samples-java/assets/46230606/d5640f20-c3c1-4300-b743-32cae7d597e1)

Test with Keploy
![doc_4](https://github.com/keploy/samples-java/assets/46230606/d29b4f47-5b69-407e-967f-6755c474f8ea)
![doc_5](https://github.com/keploy/samples-java/assets/46230606/b41d7fc5-f4c5-4c7b-99a6-9b2011414838)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

2024-01-12 19:18 UTC, Rentox98 commented
@Sonichigo Hi, I tagged you for the review of my pull request, if you have any doubts ask me please,
Thanks

2024-01-31 09:48 UTC, nehagup commented
@Rentox98 thanks for the PR, we'll review this soon. :)

2024-02-01 12:37 UTC, Sonichigo requested changes

2024-02-01 12:37 UTC, Sonichigo commented on spring-boot-postgres-graphql/README.md
> +### Use your postgres installation
There is the problem with the postresql start section here.In record mode, postgres is not connecting with application. While trying prostgres start cmd , better to remove it as with docker image postgres it works fine.

2024-02-01 12:37 UTC, Sonichigo commented
Rest LGTM and it works! Great contribution @Rentox98

2024-02-05 01:46 UTC, Rentox98 commented on spring-boot-postgres-graphql/README.md
> +### Use your postgres installation
Thanks for the review, I corrected that part.

2024-02-05 08:22 UTC, Sonichigo approved these changes

2024-02-05 08:22 UTC, merged