Updated README
keploy/samples-java pull request #71
Opened 2024-06-12 11:27 UTC by Swpn0neel

2024-06-26 09:48 UTC, Sonichigo requested changes

2024-06-26 09:48 UTC, Sonichigo commented on README.md
>  [![Slack](https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white)](https://join.slack.com/t/keploy/shared_invite/zt-12rfbvc01-o54cOG0X1G6eVJTuI_orSA)
slack  url for joining is not open for anyone without @keploy.io domain. Please update it with this slack link : - https://join.slack.com/t/keploy/shared_invite/zt-2dno1yetd-Ec3el~tTwHYIHgGI0jPe7A

2024-06-26 11:30 UTC, Swpn0neel commented
I've fixed it @Sonichigo

2024-06-27 07:41 UTC, Sonichigo approved these changes
LGTM

2024-06-27 07:41 UTC, merged